apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-deployment
spec:
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kube-news
        image: charleszt/kube-news:1.0
        imagePullPolicy: Always
        env:
          - name: DB_DATABASE
            valueFrom: 
              secretKeyRef:
                name: kube-news-secret
                key: DB_DATABASE
          - name: DB_USERNAME
            valueFrom: 
              secretKeyRef:
                name: kube-news-secret
                key: DB_USERNAME 
          - name: DB_PASSWORD
            value: Pg#123
          - name: DB_HOST
            value: postgres-database-service
        ports:
          - containerPort: 8080
            protocol: TCP
