apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: postgres-database
  accessModes:
    - ReadWriteOnce
