apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-database-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: postgres-database
  hostPath:
    path: /data
